name: Dispatch test on docs repo
on:
  repository_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  releaseTagEvent:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: younited/get-previous-tag-action@v1.0.0
        with:
          match: "0.2*"
        id: previousTag
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ggera/docs
          event-type: sdk-update
          client-payload: '{"previousTag": "${{ steps.previousTag.outputs.previous-tag }}","latestTag": "${{github.ref_name}}"}'
